import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { ModeToggle } from "@/components/ModeToggle";
import { InternationalProvider } from "@/providers/InternationalProvider";
import { ThemeProvider } from "@/providers/ThemeProvider";
import "@/styles/globals.css";
import { cn } from "@/utils";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  return (
    <html lang={locale}>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          inter.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <InternationalProvider>
            <ModeToggle />
            {children}
          </InternationalProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
